<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="25121" started-at="2020-01-02T15:08:28 CST" finished-at="2020-01-02T15:08:53 CST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25121" started-at="2020-01-02T15:08:28 CST" finished-at="2020-01-02T15:08:53 CST">
      <class name="tests.RegisterToTestEnvironment">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:tests.RegisterToTestEnvironment@56aac163]" name="beforeMethod" is-config="true" duration-ms="10533" started-at="2020-01-02T15:08:29 CST" finished-at="2020-01-02T15:08:39 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="registringInTestEnvironment(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:tests.RegisterToTestEnvironment@56aac163]" name="registringInTestEnvironment" duration-ms="3514" started-at="2020-01-02T15:08:39 CST" data-provider="getingData" finished-at="2020-01-02T15:08:43 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Zizou]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Zidan]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[nobody@gmail.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[1.23455667E8]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[realmadrid]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[realmadrid]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [TEK School – Knowledge IS power] but found [TEK School – Knowledge is power]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [TEK School – Knowledge IS power] but found [TEK School – Knowledge is power]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at tests.RegisterToTestEnvironment.registringInTestEnvironment(RegisterToTestEnvironment.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registringInTestEnvironment -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:tests.RegisterToTestEnvironment@56aac163]" name="afterMethod" is-config="true" duration-ms="264" started-at="2020-01-02T15:08:43 CST" finished-at="2020-01-02T15:08:43 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:tests.RegisterToTestEnvironment@56aac163]" name="beforeMethod" is-config="true" duration-ms="6260" started-at="2020-01-02T15:08:43 CST" finished-at="2020-01-02T15:08:49 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="registringInTestEnvironment(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:tests.RegisterToTestEnvironment@56aac163]" name="registringInTestEnvironment" duration-ms="3529" started-at="2020-01-02T15:08:49 CST" data-provider="getingData" finished-at="2020-01-02T15:08:53 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Mesut]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Ozil]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[hey@gamil.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[1.2346677E7]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[arsenal]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[arsenal]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [TEK School – Knowledge IS power] but found [TEK School – Knowledge is power]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [TEK School – Knowledge IS power] but found [TEK School – Knowledge is power]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at tests.RegisterToTestEnvironment.registringInTestEnvironment(RegisterToTestEnvironment.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registringInTestEnvironment -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:tests.RegisterToTestEnvironment@56aac163]" name="afterMethod" is-config="true" duration-ms="237" started-at="2020-01-02T15:08:53 CST" finished-at="2020-01-02T15:08:53 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- tests.RegisterToTestEnvironment -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
